# Generated by Django 4.1.7 on 2023-04-04 16:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='It',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=20)),
                ('item_name', models.CharField(max_length=100)),
                ('item_count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField(default=1)),
                ('code_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.it')),
            ],
        ),
    ]
