# Generated by Django 4.1.7 on 2023-04-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_board_attached_file_board_original_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='attached_file',
            field=models.FileField(null=True, upload_to='board/%Y-%m-%d/'),
        ),
    ]
